version: "2"

services:
    www:
        #build: ./docker/alpine/3.7/lamp/php7/
        build: ./docker/alpine/3.3/lamp/php5.3/
        volumes:
            - ./:/docker
            - ./html:/var/www/localhost/htdocs
        ports:
            - 8080:80
    mysql:
        image: mysql:5.5
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=db
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            #- ./docker/mysql/5.7/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf #5.7
            - ./docker/mysql/5.5/conf/my.cnf:/etc/mysql/my.cnf #5.5
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=password
        links:
            - mysql
        ports:
            - 8081:80
        volumes:
            - ./docker/phpmyadmin/sessions:/sessions

