version: "2"

services:
    www:
        build: ./docker/alpine/3.7/lamp/php/
        volumes:
            - ./:/docker
            - ./html:/var/www/localhost/htdocs
        ports:
            - 8080:80
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=db
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - ./docker/mysql/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=password
        links:
            - mysql
        ports:
            - 8081:80
        volumes:
            - ./docker/phpmyadmin/sessions:/sessions

